
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product_data
    password: Thanggmail25
    username: root
  jpa:
    show-sql: true
    database: mysql
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
    hibernate:
      ddl-auto: update

server:
  port: